services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talent-assessment-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./storage:/var/www/storage
    ports:
      - "8001:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_DATABASE=talent_assessment
      - DB_USERNAME=talent_user
      - DB_PASSWORD=talent_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - talent-network
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.talent-assessment.entrypoints=websecure"
      - "traefik.http.routers.talent-assessment.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.talent-assessment.tls=true"
      - "traefik.http.routers.talent-assessment.tls.certresolver=letsencrypt"
      - "traefik.http.services.talent-assessment.loadbalancer.server.port=8000"

  mysql:
    image: mysql:8.0
    container_name: talent-assessment-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: talent_assessment
      MYSQL_USER: talent_user
      MYSQL_PASSWORD: talent_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/migrations:/docker-entrypoint-initdb.d
    networks:
      - talent-network

  redis:
    image: redis:7-alpine
    container_name: talent-assessment-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - talent-network

volumes:
  mysql_data:
  redis_data:

networks:
  talent-network:
    driver: bridge
  traefik-net:
    external: true 