#!/bin/bash

echo "=== Talent Assessment - Selection Tab Test Setup ==="
echo ""

# Run the database seeder
echo "Running database seeder..."
php artisan db:seed --class=ClientTableSeeder

echo ""
echo "=== Test Accounts Created ==="
echo ""
echo "You can now test the Selection tab with these accounts:"
echo ""
echo "1. TechCorp Solutions:"
echo "   - Email: techadmin@techcorp.com"
echo "   - Password: password"
echo "   - Jobs: Software Engineer, Product Manager, Data Scientist (closed)"
echo ""
echo "2. Manufacturing Inc:"
echo "   - Email: mfgadmin@manufacturing.com"
echo "   - Password: password"
echo "   - Jobs: Production Supervisor, Quality Control Specialist, Maintenance Technician"
echo ""
echo "3. Consulting Partners:"
echo "   - Email: consultadmin@consulting.com"
echo "   - Password: password"
echo "   - Jobs: Senior Consultant, Business Analyst, Project Manager (closed)"
echo ""
echo "=== How to Test the Selection Tab ==="
echo ""
echo "1. Start your Laravel development server:"
echo "   php artisan serve"
echo ""
echo "2. Navigate to the application and login with one of the test accounts above"
echo ""
echo "3. Access the Selection tab via:"
echo "   - Direct URL: http://localhost:8000/dashboard/selection"
echo "   - Or navigate through the client dashboard"
echo ""
echo "4. The Selection tab should show:"
echo "   - A table of jobs for the client"
echo "   - Job status (Open/Closed)"
echo "   - Number of viable applicants"
echo "   - Assessment assignments"
echo "   - Links to view job details and assign assessments"
echo ""
echo "=== Expected Features ==="
echo "- View all jobs for the client"
echo "- See job status (active/inactive)"
echo "- View assessment assignments per job"
echo "- Access job details and applicant lists"
echo "- Assign assessments to jobs"
echo ""
echo "Note: The Selection tab is marked for deletion in Phase 1, but this seeder"
echo "will help you test its current functionality before removal."
